name        : nautilus-dropbox
version     : 2015.10.28
release     : 7
source     :
    - https://linux.dropbox.com/packages/nautilus-dropbox-2015.10.28.tar.bz2 : 2cd5af7f32176ab21744f057e7a917640d13fb48660042bbcfe21f214adc26aa
license     : 
    - CC-BY-ND-3.0
    - GPL-3.0
summary     : Dropbox linux client
rundeps     :
    - python-gtk2
builddeps   :
    - pkgconfig(libnautilus-extension)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(pycairo)
    - python-docutils
rundeps     :
    - python-gobject2
    - python-pygpgme
description : |
    Dropbox allows users to create a special folder on each of their computers, which Dropbox then synchronizes so that it appears to be the same folder (with the same contents) regardless of which computer is used to view it.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
