name        : nautilus-dropbox
version     : 2015.02.12
release     : 3
source     :
    - https://linux.dropbox.com/packages/nautilus-dropbox-2015.02.12.tar.bz2 : 06e152ee5a683a5911bb5147f491276d7a1ed5e05ac4065b0e9eea5e7d00ad8a
license     : 
    - CC-BY-ND-3.0
    - GPL-3.0
summary     : Dropbox linux client
rundeps     :
    - python-gtk2
builddeps   :
    - pkgconfig(libnautilus-extension)
    - pkgconfig(pygtk-2.0)
    - python-docutils
description : |
    Dropbox allows users to create a special folder on each of their computers, which Dropbox then synchronizes so that it appears to be the same folder (with the same contents) regardless of which computer is used to view it.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
