name       : nautilus-dropbox
version    : 2015.10.28
release    : 15
source     :
    - https://linux.dropbox.com/packages/nautilus-dropbox-2015.10.28.tar.bz2 : 2cd5af7f32176ab21744f057e7a917640d13fb48660042bbcfe21f214adc26aa
license    :
    - CC-BY-ND-3.0
    - GPL-3.0-or-later
component  :
    - desktop.gnome
    - ^dropbox : network.clients
summary    :
    - Dropbox extension for Nautilus
    - ^dropbox : Dropbox linux client
description: |
    - Dropbox allows users to create a special folder on each of their computers, which Dropbox then synchronizes so that it appears to be the same folder (with the same contents) regardless of which computer is used to view it.
builddeps  :
    - pkgconfig(libnautilus-extension)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(pycairo)
    - python-docutils
rundeps    :
    - dropbox
    - ^dropbox :
        - python-gobject2
        - python-pygpgme
        - python-gtk2
        - python-cairo
patterns   :
    - ^dropbox :
        - /usr/bin/dropbox
        - /usr/share/applications
        - /usr/share/icons/hicolor
        - /usr/share/man
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
